services:
  app:
    build: .
    environment:
      # Point the code at rqlite's HTTP API inside the Compose network
      RQLITE_URL: http://rqlite:4001
    depends_on:
      - rqlite
    volumes:
      - data:/data          # keep whatever .nowledge.db you still use
      - models:/models
    # expose anything your app needs (example)
    ports:
      - "3000:3000"

  rqlite:
    image: rqlite/rqlite:8.29.1   # or "latest"
    environment:
      # Ask the image to preload the vector-search extension
      SQLITE_EXTENSIONS: "sqlite-vec"
    command: ["-on-disk", "/rqlite/filedata"] # pick any dir inside the container
    volumes:
      - rqlite-data:/rqlite
    ports:
      - "4001:4001"        # HTTP API
      - "4002:4002"        # Raft (leave open if you later add nodes)

volumes:
  data:
  models:
  rqlite-data:
